### ISSUE TITLE
Multple Authentication

### ISSUE THREAD

**Issue by Lahori-Jawan** [samtgarson/nuxt-oauth#10]
I am integrating it in my blog where I need to have at-least two oauths i.e. google-plus and twitter/facebook/github etc. 

Does it support that?

**Comment by samtgarson** [comment]
Unfortunately not 😊 I will happily accept PRs but I believe that's a little out of the scope of this library, you might want to look into writing middleware using [passport](https://www.npmjs.com/package/passport) which provides strategies for most OAuth providers
