### ISSUE TITLE
redirect uri ignores HTTPS protocol

### ISSUE THREAD

**Issue by Jexordexan** [samtgarson/nuxt-oauth#3]
I'm trying to us this module on a secure domain (`https://www.my-domain.com`), but the redirect uri for the oauth request is set as `http://www.my-domain.com/auth/callback`. I think the problem is on this line:

https://github.com/samtgarson/nuxt-oauth/blob/0748fe36aef96b8df8c7f68a5d17f6473af632ff/lib/handler.js#L28

The oauth provider does not allow redirects starting with `http://`

**Comment by samtgarson** [comment]
Good catch! I'll put a fix in when I find time but I'll merge a PR if you want to put one in 👍

**Comment by Jexordexan** [comment]
Okay, I'll try to post one soon!
