### ISSUE TITLE
password grant type ?

### ISSUE THREAD

**Issue by angeenes** [samtgarson/nuxt-oauth#4]
Hi,

Do you think you can provide an example of how it works ? 
I don't get it :-( , especially the secret.vue file.

**Comment by samtgarson** [comment]
Hey @angeenes. There's a tiny example app in the [test directory](https://github.com/samtgarson/nuxt-oauth/tree/master/__tests__/fixture), but overall this follows the standard OAuth2 flow for an [Authorisation Code Grant](https://alexbilbie.com/guide-to-oauth-2-grants/#authorisation-code-grant-section-41).

If you have any more specific questions, please feel free to ask.
